Feature/button component
isdi-coders-2023/coding-adventure-Ana-Catana-front-202301-BCN pull request #1
Opened 2023-02-27 15:33 UTC by AnaCatanaR

2023-02-27 15:54 UTC, MMLORENA requested changes
Te faltan los resets y los Globals styles con colores y tipografía

2023-02-27 15:54 UTC, MMLORENA commented on src/components/Button.test.tsx
> +      const expectedButtonText = screen.getByRole("button", {
No se espera un Button Text

2023-02-27 15:54 UTC, MMLORENA commented on src/components/Button.tsx
> +import ButtonStyled from "./ButtonStyled";
Enter

2023-02-27 15:54 UTC, MMLORENA commented on src/components/ButtonStyled.tsx
> +`;
Te faltan styles del botón

2023-02-27 16:04 UTC, MMLORENA commented
@AnaCatanaR ¿qué le ha pasado a tus hooks de Husky?

2023-02-27 16:09 UTC, AnaCatanaR commented
> 
lo que me suele pasar si tengo Mac, tiro los comando "chmod ug+x .husky/pre-push". O te refieres a otra cosa?

2023-02-27 16:13 UTC, AnaCatanaR commented on src/components/Button.tsx
> +import ButtonStyled from "./ButtonStyled";
Enter de poner un espacio? Porque si no voy equivocada, veo que sí hay un salto de línea.

2023-02-27 16:14 UTC, AnaCatanaR commented on src/components/ButtonStyled.tsx
> +`;
Lo acabo de areglar y subir. gracias

2023-02-27 16:20 UTC, AnaCatanaR commented on src/components/Button.test.tsx
> +      const expectedButtonText = screen.getByRole("button", {
Oh! Ahora entiendo. Gracias Lorena! Lo cambio en un momento

2023-02-27 17:24 UTC, MMLORENA requested changes

2023-02-27 17:24 UTC, MMLORENA commented on src/GlobalStyles.tsx
> +  margin: 0;
¿Los demás h no hay que resetearles el margin?

2023-02-27 17:24 UTC, MMLORENA commented on src/GlobalStyles.tsx
> +  font-family: "Roboto";
Debería estar dentro del themeProvider o de variables de css

2023-02-27 17:24 UTC, MMLORENA commented on src/components/Button.test.tsx
> +      const expectedButton = screen.getByRole("button", {
No esperamos un Button, cambiale el naming

2023-02-27 17:24 UTC, MMLORENA commented on src/components/ButtonStyled.tsx
> +`;
El width del button en mobile y desktop debería ser igual, solo le cambia el height (es fallo del Figma que ya está corregido) y la Opacity solo es de la clase disabled del button

2023-02-28 15:28 UTC, AnaCatanaR commented on src/GlobalStyles.tsx
> +  margin: 0;
Lo acabo de hacer. Gracias!

2023-02-28 15:28 UTC, AnaCatanaR commented on src/GlobalStyles.tsx
> +  margin: 0;
reseteadas todas 6.

2023-02-28 15:29 UTC, AnaCatanaR commented on src/GlobalStyles.tsx
> +  font-family: "Roboto";
lo acabo de hacer

2023-02-28 15:29 UTC, AnaCatanaR commented on src/components/Button.test.tsx
> +      const expectedButton = screen.getByRole("button", {
naming del Button cambiado

2023-02-28 15:30 UTC, AnaCatanaR commented
lo acabo de hacer. gracias

2023-02-28 16:01 UTC, AnaCatanaR commented on src/components/ButtonStyled.tsx
> +`;
arreglado Lorena, gracias!

2023-03-01 15:07 UTC, catatarelli commented on src/components/Button.tsx
> +import ButtonStyled from "./ButtonStyled";
yo veo la interface en la linea dos, por lo que no hay espacio entre el import y la interface

2023-03-01 15:12 UTC, AnaCatanaR commented on src/components/Button.test.tsx
> +  describe("When it's calls with the text 'Sign up'", () => {
Gracias Cata, lo acabo de modificar. si consideras oportuno me lo podrías aprobar?

2023-03-01 15:19 UTC, catatarelli approved these changes

2023-03-01 15:19 UTC, catatarelli commented on src/styles/styled.d.ts
> +declare module "styled-components" {
hace falta este declare? fijate en la docu de styled components el createGlobalStyle, ahora para la proxima

2023-03-01 15:35 UTC, merged